config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :users
  resource :login
  post '/' => 'posts#index'
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  # validates :subject, presence: true
  validates :text,
  presence: true,
  length: { maximum: 140 }
  # validates :name,    presence: true

  # has_secure_password
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # self.primary_key = "name"

  # def self.colors
  #   [["red",    "red"],
  #   [ "blue",   "blue"],
  #   [ "green",  "green"],
  #   [ "purple", "purple"],
  #   [ "brown",  "brown"],
  #   [ "gray",   "gray"],
  #   [ "lime",   "lime"]]
  # end

  enum color: %i(red blue green purple brown gray lime)

  validates :name,
  presence: true,
  length: { minimum: 4, maximum: 10 }

  validates :password,
  length: { minimum: 4, maximum: 10 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #protect_from_forgery

  def current_user
    if session[:user_id]
      # @current_userがnilかfalseならログインユーザーを代入
      if User.find_by_id(session[:user_id])
        @current_user ||= User.find_by_id(session[:user_id])
      else
        @current_user = nil
        session[:user_id] = nil
      end
    end
  end

  helper_method :current_user
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def create
    reset_session
    if params.key?(:name) || params.key?(:pass)
      user = User.find_by_name params[:name]
      if user && user.authenticate(params[:pass])
        session[:user_id] = user.id
        redirect_to root_path
      else
        session[:user_id] = nil
        redirect_to root_path, alert: 'ユーザまたはパスワードが間違っています'
      end
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post

  def index
    if current_user == nil
      @post = Post.new
    else
      @post = current_user.posts.new
    end
  end

  def create
    @user = User.find(current_user)
  	@post = @user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render "index"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

    def post_params
    	params[:post].permit(:text)
    end

    def set_post
      @posts = Post.all
      @posts = Post.order("id").reverse_order
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "ユーザ #{@user.name} の作成に成功しました！"
    else
      render 'new'
    end
  end

  def destroy
  end

  private

    def user_params
      params[:user].permit(:name, :color, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tvv!++er</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user != nil %>
  <nav class="bg_<%= current_user.color %>">
<% else %>
  <nav>
<% end %>

  <h1><%= link_to 'Tvv!++er', root_path %></h1>

  <div id="login">
    <% if current_user != nil %>
      <h2><%= current_user.name %> でログインしています</h2>
    <% else %>
      <% if notice %>
        <h2><%= flash[:notice] %></h2>
      <% end %>
      <% if alert %>
        <h2><%= flash[:alert] %></h2>
      <% end %>
    <% end %>

    <% if current_user == nil %>
      <%= form_tag login_path do %>
        ユーザ<%= text_field_tag :name, params[:name] %>
        パスワード<%= password_field_tag :pass, params[:pass] %>
        <%= submit_tag "ログイン" %>
      <% end %>
    <% else %>
      <%= button_to 'ログアウト', login_path, :method => :delete, :data => { :confirm => '本当にログアウトしますか？'  } %>
    <% end %>
  </div>
</nav>

<div id="container">

  <%= yield %>

</div>

</body>
</html>

app/views/posts/index.html.erb
<%= form_for @post do |f| %>

  <!-- エラー処理 -->
  <% @post.errors.full_messages.each do |message| %>
    <p class="error"><%= message %></p>
  <% end %>

  <!-- 入力フォーム -->
  <div class="newpost">
    <% if current_user != nil %>
      <%= f.text_area :text, :class => "border_"+current_user.color %>
      <p><%= f.submit "つぶやく", :class => "bg_"+current_user.color %></p>
    <% else %>
      <%= link_to "新しくユーザを作成する", new_user_path, :class => "newuser" %>
    <% end %>
  </div>
<% end %>

<!-- Post一覧 -->
<ul class="posts">
  <% @posts.each do |post| %>
    <% user = User.find(post.user_id) %>

    <li>
      <div class="post border_<%= user.color %>">

        <!-- キャプション -->
        <div class="post_caption bg_<%= user.color %>">
          <h2><%= user.name %></h2>
        </div>

        <!-- 本文 -->
        <div class="post_text">
          <%= simple_format(h(post.text)) %>
          <p class="date"><%= post.created_at %></p>
        </div>

        <!-- 削除ボタン -->
        <% if current_user != nil %>
          <% if current_user == user || current_user.name == "admin" %>
            <div class="delete">
              <%= form_for post, :url => post_path(post.id), :html => { :method => :delete } do |f| %>
                <span><%= f.submit "削除", :class => "bg_"+user.color , :data => { :confirm => '本当に削除しますか？' } %></span>
              <% end %>
            </div>
          <% end %>
        <% end %>

      </div>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <!-- エラー処理 -->
  <% @user.errors.full_messages.each do |message| %>
    <p class="error"><%= message %></p>
  <% end %>

  <table class="newuser">
    <tr>
      <td>名前</td><td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>色</td><td><%= f.select :color, User.colors.keys %></td>
    </tr>
    <tr>
      <td>パスワード</td><td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td>パスワード（確認）</td><td><%= f.password_field :password_confirmation %>
    </tr>
  </table>
  <%= f.submit "作成", :class => "wide_button" %>
<% end %>